# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87d6036375eb8fc78fbfc4ae1aab48881bf67fde62fc32349856243d220d67fa57ca14c9d9400bad1361b161939cd11ddd8be7304677f71a487cff7669365f9

test:
  secret_key_base: 7c04a714604b80f50f5da883eaa65ba896f1176298c5c1f5be1be958deb7bc331263738248041137f34dc9bfdb141351f0f1a2c778262aa01a52f87c455a8e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
